name: .NET Core CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    - name: Install dependencies
      run: dotnet restore ./AgriWeatherTracker/API/AgriWeatherTracker.csproj

    - name: Build
      run: dotnet build --no-restore ./AgriWeatherTracker/API/AgriWeatherTracker.csproj

    - name: Test
      run: dotnet test --no-build --verbosity normal ./AgriWeatherTracker/tests/WeatherTracker.Tests/WeatherTracker.Tests.csproj

    - name: Publish
      run: dotnet publish ./AgriWeatherTracker/API/AgriWeatherTracker.csproj -c Release -o ./publish

    - name: 'Login via Az module'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Deploy to Azure WebApp'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'cropWeatherTracker'
        package: './publish'
        slot-name: 'production' # or your specific slot name, if applicable
