name: .NET Core CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '7.0.x'

    - name: Install dependencies
      run: dotnet restore ./AgriWeatherTracker/API/AgriWeatherTracker.csproj

    - name: Build
      run: dotnet build --no-restore ./AgriWeatherTracker/API/AgriWeatherTracker.csproj

    - name: Test
      run: dotnet test --no-build --verbosity normal ./AgriWeatherTracker/tests/WeatherTracker.Tests/WeatherTracker.Tests.csproj
